package model

type Stock struct {
	Name                 string  `json:"name"`
	Quantity             int     `json:"quantity"`
	Price                float64 `json:"price"`
	Symbol               string  `json:"symbol"`
	Exchange             string  `json:"exchange"`
	MarketCap            float64 `json:"market_cap"`
	PEratio              float64 `json:"pe_ratio"`
	DividendYield        float64 `json:"dividend_yield"`
	High52Week           float64 `json:"high_52_week"`
	Low52Week            float64 `json:"low_52_week"`
	Volume               int     `json:"volume"`
	AvgVolume            int     `json:"avg_volume"`
	EPS                  float64 `json:"eps"`
	SharesOutstanding    int     `json:"shares_outstanding"`
	CurrentPrice         float64 `json:"current_price"`
	BookValue            float64 `json:"book_value"`
	ROCE                 float64 `json:"roce"`
	ROE                  float64 `json:"roe"`
	FaceValue            float64 `json:"face_value"`
	Industry             string  `json:"industry"`
	Sector               string  `json:"sector"`
	Beta                 float64 `json:"beta"`
	DividendRate         float64 `json:"dividend_rate"`
	ExDividendDate       string  `json:"ex_dividend_date"`
	DividendPayDate      string  `json:"dividend_pay_date"`
	MarketOpen           bool    `json:"market_open"`
	MarketClose          bool    `json:"market_close"`
	Change52Week         float64 `json:"change_52_week"`
	ShortRatio           float64 `json:"short_ratio"`
	EBITDA               float64 `json:"ebitda"`
	Revenue              float64 `json:"revenue"`
	GrossProfit          float64 `json:"gross_profit"`
	OperatingIncome      float64 `json:"operating_income"`
	NetIncome            float64 `json:"net_income"`
	Cash                 float64 `json:"cash"`
	Debt                 float64 `json:"debt"`
	FreeCashFlow         float64 `json:"free_cash_flow"`
	OperatingMargin      float64 `json:"operating_margin"`
	ProfitMargin         float64 `json:"profit_margin"`
	ReturnOnAssets       float64 `json:"return_on_assets"`
	ReturnOnEquity       float64 `json:"return_on_equity"`
	DebtToEquity         float64 `json:"debt_to_equity"`
	CurrentRatio         float64 `json:"current_ratio"`
	QuickRatio           float64 `json:"quick_ratio"`
	InterestCoverage     float64 `json:"interest_coverage"`
	PayoutRatio          float64 `json:"payout_ratio"`
	SharesFloat          int     `json:"shares_float"`
	InstitutionalOwnership float64 `json:"institutional_ownership"`
	InsiderOwnership     float64 `json:"insider_ownership"`
	ForwardPE            float64 `json:"forward_pe"`
	TrailingPE           float64 `json:"trailing_pe"`
	PEG                  float64 `json:"peg"`
	PriceToSales         float64 `json:"price_to_sales"`
	PriceToBook          float64 `json:"price_to_book"`
	EnterpriseValue      float64 `json:"enterprise_value"`
	EVToEBITDA           float64 `json:"ev_to_ebitda"`
	EVToRevenue          float64 `json:"ev_to_revenue"`
	FiscalYearEnd        string  `json:"fiscal_year_end"`
	NextEarningsDate     string  `json:"next_earnings_date"`
	DividendFrequency    string  `json:"dividend_frequency"`
	AnalystRating        float64 `json:"analyst_rating"`
	PriceTarget          float64 `json:"price_target"`
	EarningsGrowth       float64 `json:"earnings_growth"`
	RevenueGrowth        float64 `json:"revenue_growth"`
	OperatingCashFlow    float64 `json:"operating_cash_flow"`
	LeveredFreeCashFlow  float64 `json:"levered_free_cash_flow"`
	SharesShort          int     `json:"shares_short"`
	ShortPercentOfFloat  float64 `json:"short_percent_of_float"`
	SharesShortPriorMonth int    `json:"shares_short_prior_month"`
}
